# Generated by Django 5.1 on 2024-09-26 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=30)),
                ('amount_of_employees', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tech_support_employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pile_name', models.CharField(max_length=30)),
                ('sur_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Dep_Chief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pile_name', models.CharField(max_length=30)),
                ('sur_name', models.CharField(max_length=30)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appIncidencias.department')),
            ],
        ),
        migrations.CreateModel(
            name='Non_Tech_employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pile_name', models.CharField(max_length=30)),
                ('sur_name', models.CharField(max_length=30)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIncidencias.department')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('summary', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('non_tec_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIncidencias.non_tech_employee')),
                ('tec_supp_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIncidencias.tech_support_employee')),
            ],
        ),
    ]
