# Generated by Django 4.2.16 on 2024-11-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appIncidencias', '0002_tech_support_employee_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='amount_of_employees',
        ),
        migrations.AlterField(
            model_name='department',
            name='dep_name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='tech_support_employee',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='tech_support_employee',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
