# Generated by Django 4.2.16 on 2024-11-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appIncidencias', '0003_remove_department_amount_of_employees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Dep_Chief',
        ),
    ]
