# Generated by Django 4.2.16 on 2024-11-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appIncidencias', '0004_alter_department_id_delete_dep_chief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tech_support_employee',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
