# Generated by Django 4.2.16 on 2024-11-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appIncidencias', '0005_alter_tech_support_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='non_tech_employee',
            name='id',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
