# Generated by Django 4.2.16 on 2024-11-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appIncidencias', '0006_alter_non_tech_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
